package main

type Command int

const (
	MPUSH Command = iota
	MINSERT
	MGET
	MSET
	MDEL
	MLEN
	MPRINT

	FPUSHH
	FPUSHT
	FPUSHA
	FPUSHB
	FDELH
	FDELT
	FDELA
	FDELB
	FDEL
	FFIND
	FPRINT
	FPRINTR

	LPUSHH
	LPUSHT
	LPUSHA
	LPUSHB
	LDELH
	LDELT
	LDELA
	LDELB
	LDEL
	LFIND
	LPRINT
	LPRINTR

	SPUSH
	SPOP
	SPRINT

	QPUSH
	QPOP
	QPRINT

	TINSERT
	TFIND
	TCOMPLETE
	TPRINT

	PRINT
	UNKNOWN
)

var commandNames = map[string]Command{
	"MPUSH": MPUSH, "MINSERT": MINSERT, "MGET": MGET, "MSET": MSET,
	"MDEL": MDEL, "MLEN": MLEN, "MPRINT": MPRINT,

	"FPUSHH": FPUSHH, "FPUSHT": FPUSHT, "FPUSHA": FPUSHA, "FPUSHB": FPUSHB,
	"FDELH": FDELH, "FDELT": FDELT, "FDELA": FDELA, "FDELB": FDELB,
	"FDEL": FDEL, "FFIND": FFIND, "FPRINT": FPRINT, "FPRINTR": FPRINTR,

	"LPUSHH": LPUSHH, "LPUSHT": LPUSHT, "LPUSHA": LPUSHA, "LPUSHB": LPUSHB,
	"LDELH": LDELH, "LDELT": LDELT, "LDELA": LDELA, "LDELB": LDELB,
	"LDEL": LDEL, "LFIND": LFIND, "LPRINT": LPRINT, "LPRINTR": LPRINTR,

	"SPUSH": SPUSH, "SPOP": SPOP, "SPRINT": SPRINT,

	"QPUSH": QPUSH, "QPOP": QPOP, "QPRINT": QPRINT,

	"TINSERT": TINSERT, "TFIND": TFIND, "TCOMPLETE": TCOMPLETE, "TPRINT": TPRINT,

	"PRINT": PRINT,
}

func toCommand(text string) Command {
	command, ok := commandNames[text]
	if !ok {
		return UNKNOWN
	}
	return command
}